controllers/preparo_controller.py
from flask import Blueprint
from flask import jsonify, render_template, request, url_for, flash, redirect
from Semaninha_MVC.controllers import forms, produto_final_controller
from Semaninha_MVC.models import utils, preparo_model, materia_prima_model, produto_final_model

# create a blueprint for the preparo routes
preparo_bp = Blueprint('preparo_bp', __name__)

def atualiza_custo_rendimento_preparo(id_preparo, conn):
    ficha = preparo_model.busca_qtd_custo_preparo(id_preparo=id_preparo, id_materia_prima=None, conn=conn)

    qtd_preparo = 0
    custo_preparo = 0

    # calcula o peso final produzido pela receita e o custo
    for materia_prima in ficha:
        qtd_preparo += (materia_prima[0] * materia_prima[3]) / materia_prima[2]
        custo_preparo += materia_prima[1]

    preparo_model.atualiza_rendimento_custo_preparo(qtd_preparo, custo_preparo, id_preparo, conn)

@preparo_bp.route("/novo_preparo", methods=["GET", "POST"])
def novo_preparo():
    conn = utils.get_db()
    form = forms.PreparoForm()

    form.unidade_medida.choices = utils.unidade_medida_choices(conn)

    if form.validate_on_submit():
        id_inserted = preparo_model.insert(form.preparo.data,
                                           form.unidade_medida.data,
                                           form.modo_preparo.data,
                                           conn)

        flash("Preparo {} inserido com sucesso".format(request.form.get("preparo")), "success")
        return redirect(url_for("preparo_bp.preparo", id_preparo=id_inserted))

    return render_template("preparo/novo_preparo.html", form=form)

@preparo_bp.route("/preparos")
def preparos():
    conn = utils.get_db()
    preparos_db = preparo_model.busca_todos_preparos(conn)

    preparos = []

    for preparo in preparos_db:
        ficha = preparo_model.tem_ficha_tecnica(preparo[0], conn)

        if ficha:
            tem_ficha = True
        else:
            tem_ficha = False

        preparo = {
            "id"           : preparo[0],
            "preparo"      : preparo[1],
            "id_unid_med"  : preparo[2],
            "rendimento"   : preparo[3],
            "custo_preparo": preparo[4],
            "modo_preparo" : preparo[5],
            "tem_ficha"    : tem_ficha
        }
        preparos.append(preparo)

    return render_template("preparo/preparos.html", preparos=preparos)

@preparo_bp.route("/preparo/<int:id_preparo>")
def preparo(id_preparo):
    conn = utils.get_db()
    preparo_from_db = preparo_model.busca_dados_preparo(id_preparo, conn)

    try:
        preparo = {
                "id": preparo_from_db[0],
                "preparo": preparo_from_db[1],
                "id_unid_med": preparo_from_db[2],
                "unidade_medida": preparo_from_db[3],
                "rendimento": round(preparo_from_db[4],2),
                "custo_preparo": preparo_from_db[5],
                "modo_preparo": preparo_from_db[6]
            }
    except:
        preparo = {}

    if preparo:
        # busca os dados da ficha tecnica do preparo
        ficha_from_db = preparo_model.busca_ficha_preparo(id_preparo, conn)

        fichas = []

        for row in ficha_from_db:
            row = {
                "id_materia_prima" : row[0],
                "materia_prima"    : row[1],
                "qtd_materia_prima": row[2],
                "id_unid_med"      : row[3],
                "unidade_medida"   : row[4],
                "medida_caseira"   : row[5],
                "custo_material"   : row[6]
            }
            fichas.append(row)

        fichaPreparoForm = forms.NewFichaPreparoForm()
        fichaPreparoForm.id_preparo.data = id_preparo

        materias_primas = [(str(mp[0]), mp[1]) for mp in materia_prima_model.busca_todas_mp(conn, id_preparo, preparo['id_unid_med'])]
        fichaPreparoForm.materia_prima.choices = materias_primas

        deletePreparo = forms.DeleteButton()
        deleteItemFicha = forms.DeleteButton()

        return render_template("preparo/preparo.html",
                               fichaPreparoForm=fichaPreparoForm,
                               preparo=preparo,
                               fichas=fichas,
                               deletePreparo=deletePreparo,
                               deleteItemFicha=deleteItemFicha)
    return redirect(url_for("index"))

@preparo_bp.route("/fichapreparo/new/<int:id_preparo>/<int:id_unid_med>", methods=["POST"])
def new_ficha_preparo(id_preparo, id_unid_med):
    conn = utils.get_db()
    form = forms.NewFichaPreparoForm()

    materias_primas = [(str(mp[0]), mp[1]) for mp in materia_prima_model.busca_todas_mp(conn, id_preparo, id_unid_med)]
    form.materia_prima.choices = materias_primas

    if form.validate_on_submit():
        preparo_model.insert_preparo_mp(form.id_preparo.data,
                                        form.materia_prima.data,
                                        form.qtd_materia_prima.data,
                                        form.medida_caseira.data,
                                        form.custo_material.data,
                                        conn)

        #chama a função para atualizar o custo do preparo de acordo com os ingredientes informados
        atualiza_custo_rendimento_preparo(form.id_preparo.data, conn)

        # Busca os produtos que utilizam o preparo alterado
        produto_final_controller.atualiza_custo_produto_preparo(id_preparo=form.id_preparo.data, conn=conn)

    return redirect(url_for('preparo_bp.preparo', id_preparo=form.id_preparo.data))

@preparo_bp.route("/fichapreparo/<int:id_preparo>/<int:id_materia_prima>/delete", methods=["POST"])
def delete_preparo_materia_prima(id_preparo, id_materia_prima):
    conn = utils.get_db()
    preparo_model.delete_preparo_materia_prima(id_preparo, id_materia_prima, conn)

    id_preparo_str = str(id_preparo)
    atualiza_custo_rendimento_preparo(id_preparo_str, conn)
    # Busca os produtos que utilizam o preparo alterado
    produto_final_controller.atualiza_custo_produto_preparo(id_preparo=id_preparo_str, conn=conn)

    flash("Item da ficha deletado com sucesso.")

    return redirect(url_for('preparo_bp.preparo', id_preparo=id_preparo))

@preparo_bp.route("/deletepreparo/<int:id_preparo>/delete", methods=["POST"])
def delete_preparo(id_preparo):
    conn = utils.get_db()
    preparo_model.delete_preparo(id_preparo, conn)

    flash("Preparo deletado com sucesso.")

    return redirect(url_for('preparo_bp.preparos'))

@preparo_bp.route("/custo_preparo/<int:id_preparo>/<float(signed=True):qtd_preparo>")
def custo_preparo(id_preparo, qtd_preparo):
    conn = utils.get_db()
    custo_preparo = preparo_model.busca_custo_preparo(id_preparo, conn)

    custo = round( ( float(custo_preparo[1]) /float(custo_preparo[0]) ) * float(qtd_preparo),2)
    return jsonify(custo=custo)

templates/preparo/novo_preparo.html
{% extends 'base.html' %}
{% set active_page = 'novo_preparo' %}
{% from "_error_messages.html" import field_error_messages, error_messages %}
{% block title %}Novo preparo - {% endblock %}

{% block content %}
<div class="row">
  <div class="col-lg-7 offset-lg-2 my-5">
    <h1>Novo preparo</h1><hr>
    <form method="POST" action="{{ url_for('preparo_bp.novo_preparo') }}" enctype="multipart/form-data">
      {{ form.hidden_tag() }}
      {{ error_messages(form.errors) }}
      <div class="form-group">
        {{ form.preparo.label }}
        {{ form.preparo(class="form-control") }}
        {{ field_error_messages(form.preparo) }}
      </div>
       <div class="form-group">
        {{ form.unidade_medida.label }}
        {{ form.unidade_medida(class="form-control") }}
        {{ field_error_messages(form.unidade_medida) }}
      </div>
      <div class="form-group">
        {{ form.modo_preparo.label }}
        {{ form.modo_preparo(class="form-control", rows="3") }}
        {{ field_error_messages(form.modo_preparo) }}
      </div>
      <hr>
      {{ form.submit(class="btn btn-primary form-control") }}
    </form>
  </div>
</div>
{% endblock %}

templates/preparo/preparo.html
{% extends 'base.html' %}
{% from "_error_messages.html" import field_error_messages, error_messages %}
{% block title %}{{ preparo.preparo }} - {% endblock %}

{% block content %}
<div class="row">
  <div class="col-lg-9">
    <div class="card mt-4">
      <div class="card-body">
        <h3 class="card-title">{{ preparo.preparo }}</h3>
        <p class="card-text"><b>Rendimento: </b>{{ preparo.rendimento | safe }} {{ preparo.unidade_medida | safe }}</p>
        <p class="card-text"><b>Custo:</b> {{ "$%.2f" | format(preparo.custo_preparo) }}</p>
        <p class="card-text"><b>Modo preparo: </b>{{ preparo.modo_preparo }}</p><br><br>
        <form class="delete-form" method="POST" action="{{ url_for('preparo_bp.delete_preparo', id_preparo=preparo.id) }}">
          {{ deletePreparo.hidden_tag() }}
          {{ deletePreparo.submit(class="btn btn-danger", onclick="return confirm('Are you sure you want to delete this item?');") }}
        </form>
      </div>
    </div>

    <div class="card card-outline-secondary my-4">
      <div class="card-header">
        Ficha técnica
      </div>
      <div class="card-body">
        <hr class="form-border">
        {% if fichas %}
          {% for ficha in fichas %}
            <b>{{ ficha.materia_prima }}</b> - {{ ficha.qtd_materia_prima }} {{ ficha.unidade_medida }} - {{ ficha.medida_caseira }} - R$ {{ficha.custo_material }}
            <form class="delete-form" method="POST" action="{{ url_for('preparo_bp.delete_preparo_materia_prima', id_preparo=preparo.id, id_materia_prima=ficha.id_materia_prima) }}">
              {{ deleteItemFicha.hidden_tag() }}
              {{ deleteItemFicha.submit(class="btn btn-danger", onclick="return confirm('Are you sure you want to delete this item?');") }}
            </form>
            <br>
          {% endfor %}
        {% else %}
          <p class="placeholder-materia_prima">Insira aqui a ficha técnica do produto.</p>
        {% endif %}
        <hr>
        <form class="ficha-form" action="{{ url_for('preparo_bp.new_ficha_preparo',
                                                     id_preparo=preparo.id,
                                                     id_unid_med=preparo.id_unid_med) }}" method="POST">
          {{ fichaPreparoForm.hidden_tag() }}
          {{ error_messages(fichaPreparoForm.errors) }}
          <div class="form-group">
            <b>Atenção: aqui aparecem apenas matérias primas com a mesma unidade de medida do preparo.</b><br><br>
            {{ fichaPreparoForm.materia_prima.label }}
            {{ fichaPreparoForm.materia_prima(class="form-control") }}
            {{ field_error_messages(fichaPreparoForm.materia_prima) }}
          </div>
          <div class="form-group">
            {{ fichaPreparoForm.unidade_medida.label }}
            {{ fichaPreparoForm.unidade_medida(class="form-control") }}
          </div>
          <div class="form-group">
            {{ fichaPreparoForm.qtd_materia_prima.label }} (produto cru / bruto)
            {{ fichaPreparoForm.qtd_materia_prima(class="form-control") }}
          </div>
          <div class="form-group">
            {{ fichaPreparoForm.medida_caseira.label }}
            {{ fichaPreparoForm.medida_caseira(class="form-control") }}
          </div>
          <div class="form-group">
            {{ fichaPreparoForm.custo_material.label }}
            {{ fichaPreparoForm.custo_material(class="form-control", type="number") }}
          </div>
          {{ fichaPreparoForm.submit(class="btn btn-primary") }}
          <span class="ficha-error"></span>
        </form>

      </div>
    </div>
  </div>
</div>
{% endblock %}
{% block javascript %}
<script src="{{ url_for("static", filename="js/unid_med.js") }}"></script>
<script src="{{ url_for("static", filename="js/custo_materia_prima.js") }}"></script>
{% endblock %}

templates/preparo/preparos.html
{% extends 'base.html' %}

{% block content %}
  <div class="col-lg-9">
      <div class="row my-5 card-wrapper">
        <table border="1">
        {% if preparos %}
        {% for preparo in preparos %}
            <tr><td>
              <p class="card-text">
                <a href="{{ url_for('preparo_bp.preparo', id_preparo=preparo.id) }}">{{ preparo.preparo }}</a>
                {% if preparo.tem_ficha %}
                  - <span class="text-danger"><b>Ficha técnica ok </b></span>
                {% endif %}
              </p>
            </td></tr>
        {% endfor %}
        {% else %}
        <h1 class="offset-lg-3">No items to show.</h1>
        {% endif %}
        </table>
      </div>
  </div>
{% endblock %}
{% block javascript %}
{% endblock %}