controllers/pedido_controller.py
from datetime import date
from flask import Blueprint
from flask import render_template, url_for, flash, redirect
from Semaninha_MVC.controllers.forms import PedidoForm, NewPedidoProdutoForm, DeleteButton, PedidoClienteForm
from Semaninha_MVC.controllers import general_controller
from Semaninha_MVC.models import cliente_model, pedido_model, produto_final_model, utils, cardapio_model

# create a blueprint for the cardapio routes
pedido_bp = Blueprint('pedido_bp', __name__)

@pedido_bp.route("/novo_pedido", methods=["GET", "POST"])
def novo_pedido():
    conn = utils.get_db()
    form = PedidoForm()

    # Busca os clientes para opção
    clientes = [(str(cliente[0]), cliente[1]) for cliente in cliente_model.busca_todos_clientes(conn)]
    form.cliente.choices = clientes

    # Busca os status de pagamento
    form.status_pagamento.choices = general_controller.busca_status("Pagamento", conn)

    # Busca os status de entrega
    form.status_entrega.choices = general_controller.busca_status("Entrega", conn)

    if form.validate_on_submit():
        # Process the form data
        pedido_model.insert(form, conn)

        # Redirect to some page
        flash("Pedido inserido com sucesso", "success")
        return redirect(url_for("index"))

    return render_template("pedido/novo_pedido.html", form=form)

@pedido_bp.route("/pedidos")
def pedidos():
    conn = utils.get_db()
    pedidos_db = pedido_model.busca_todos_pedidos(conn)
    pedidos = []

    for row in pedidos_db:
        pedido = {
            "id"               : row[0],
            "cliente"          : row[1],
            "data_pedido"      : row[2],
            "data_entrega"     : row[3],
            "valor"            : row[4],
            "status_pagamento" : utils.busca_status_por_id(row[5], conn),
            "status_entrega"   : utils.busca_status_por_id(row[6], conn)
        }
        pedidos.append(pedido)

    return render_template("pedido/pedidos.html", pedidos=pedidos)

@pedido_bp.route("/pedido/<int:id_pedido>")
def pedido(id_pedido):
    conn = utils.get_db()
    # busca os dados do pedido
    pedido_from_db = pedido_model.busca_dados_pedido(id_pedido, conn)

    try:
        pedido = {
            "id": pedido_from_db[0],
            "id_cliente": pedido_from_db[1],
            "nome": pedido_from_db[2],
            "data_pedido": pedido_from_db[3],
            "data_entrega": pedido_from_db[4],
            "valor": pedido_from_db[5],
            "status_pagamento": utils.busca_status_por_id(pedido_from_db[6], conn),
            "status_entrega": utils.busca_status_por_id(pedido_from_db[7], conn),
            "observacoes": pedido_from_db[8]
        }
    except:
        pedido = {}

    if pedido:
        # busca os produtos que compôem o pedido
        pedido_produto_from_db = pedido_model.busca_pedido_produto(id_pedido, conn)
        pedido_produto = []

        for row in pedido_produto_from_db:
            row = {
                "id_pedido"  : row[0],
                "id_produto" : row[1],
                "produto"    : row[2],
                "qtd_produto": row[3]

            }
            pedido_produto.append(row)

        pedidoProdutoForm = NewPedidoProdutoForm()
        pedidoProdutoForm.id_pedido.data = id_pedido

        produtos = [(str(produto[0]), produto[1]) for produto in produto_final_model.busca_todos_produtos(conn)]
        pedidoProdutoForm.produto.choices = produtos

        deletePedido = DeleteButton()
        deletePedidoProduto = DeleteButton()

        return render_template("pedido/pedido.html",
                               pedidoProdutoForm=pedidoProdutoForm,
                               pedido=pedido,
                               pedido_produto=pedido_produto,
                               deletePedido=deletePedido,
                               deletePedidoProduto=deletePedidoProduto)
    return redirect(url_for("index"))

@pedido_bp.route("/pedidoproduto/new", methods=["POST"])
def new_pedido_produto():
    conn = utils.get_db()
    form = NewPedidoProdutoForm()

    produtos = [(str(produto[0]), produto[1]) for produto in produto_final_model.busca_todos_produtos(conn)]
    form.produto.choices = produtos

    if form.validate_on_submit():
        pedido_model.insert_pedido_produto(form, conn)

    return redirect(url_for('pedido_bp.pedido', id_pedido=form.id_pedido.data))

@pedido_bp.route("/delete_pedido/<int:id_pedido>/<id_cliente>/delete", methods=["POST"])
def delete_pedido(id_pedido, id_cliente):
    conn = utils.get_db()
    pedido_model.delete_pedido(id_pedido, conn)

    flash("Pedido deletado com sucesso.")

    if id_cliente == 'None':
        return redirect(url_for('pedido_bp.pedidos'))
    else:
        return redirect(url_for('cliente_bp.cliente', id_cliente=id_cliente))

@pedido_bp.route("/pedidoproduto/<int:id_pedido>/<int:id_produto>/delete", methods=["POST"])
def delete_pedido_produto(id_pedido, id_produto):
    conn = utils.get_db()
    pedido_model.delete_pedido_produto(id_pedido, id_produto, conn)

    flash("Produto deletado com sucesso.")

    return redirect(url_for('pedido_bp.pedido', id_pedido=id_pedido))

@pedido_bp.route("/novo_pedido_cliente", methods=["GET", "POST"])
def novo_pedido_cliente():
    conn = utils.get_db()
    form = PedidoClienteForm()
    form.data_entrega.choices = cardapio_model.busca_datas_entrega(date=date.today(), conn=conn)

    # Busca os produtos que estão disponíveis no cardápio no dia atual
    produtos_cardapio_from_db = cardapio_model.busca_produtos_cardapio(date=date.today(), conn=conn)

    produtos = []

    for row in produtos_cardapio_from_db:
        produto = {
            "id": row[0],
            "produto": row[1],
            "qtd_produto": row[2],
            "preco_venda": row[3],
            "descricao": row[4]
        }

        produtos.append(produto)

    if form.validate_on_submit():
        flash("Pedido inserido com sucesso", "success")
        return redirect(url_for("pedido_bp.novo_pedido"))

    return render_template("pedido/novo_pedido_cliente.html", form=form, produtos=produtos)

templates/pedido/novo_pedido.html
{% extends 'base.html' %}
{% set active_page = 'novo_pedido' %}
{% from "_error_messages.html" import field_error_messages, error_messages %}
{% block title %}Novo pedido{% endblock %}

{% block content %}
<div class="row">
  <div class="col-lg-7 offset-lg-2 my-5">
    <h1>Novo pedido</h1><hr>
    <form method="POST" action="{{ url_for('pedido_bp.novo_pedido') }}" enctype="multipart/form-data">
      {{ form.hidden_tag() }}
      {{ error_messages(form.errors) }}
      <div class="form-group">
        {{ form.cliente.label }}
        {{ form.cliente(class="form-control") }}
        {{ field_error_messages(form.cliente) }}
      </div>
      <div class="form-group">
        {{ form.data_pedido.label }}
        {{ form.data_pedido(class="form-control") }}
        {{ field_error_messages(form.data_pedido) }}
      </div>
      <div class="form-group">
        {{ form.data_entrega.label }}
        {{ form.data_entrega(class="form-control") }}
        {{ field_error_messages(form.data_entrega) }}
      </div>
      <div class="form-group">
        {{ form.valor.label }}
        {{ form.valor(class="form-control", type="number") }}
        {{ field_error_messages(form.valor) }}
      </div>
      <div class="form-group">
        {{ form.status_pagamento.label }}
        {{ form.status_pagamento(class="form-control") }}
        {{ field_error_messages(form.status_pagamento) }}
      </div>
      <div class="form-group">
        {{ form.status_entrega.label }}
        {{ form.status_entrega(class="form-control") }}
        {{ field_error_messages(form.status_entrega) }}
      </div>
      <div class="form-group">
        {{ form.observacoes.label }}
        {{ form.observacoes(class="form-control", rows="3") }}
        {{ field_error_messages(form.observacoes) }}
      </div>
      <hr>
      {{ form.submit(class="btn btn-primary form-control") }}
    </form>
  </div>
</div>
{% endblock %}
{% block javascript %}
<!-- <script src="{{ url_for('static', filename='js/subcategory.js') }}"> </script> -->

{% endblock %}

templates/pedido/novo_pedido_cliente.html
{% extends 'base.html' %}
{% set active_page = 'novo_pedido' %}
{% from "_error_messages.html" import field_error_messages, error_messages %}
{% block title %}Novo pedido{% endblock %}

{% block content %}
<div class="row">
  <div class="col-lg-7 offset-lg-2 my-5">
    <h1>Novo pedido - Cliente</h1><hr>
    <form method="POST" action="{{ url_for('pedido_bp.novo_pedido_cliente') }}" enctype="multipart/form-data">
        {{ form.csrf_token }}
        {{ error_messages(form.errors) }}
      <div class="form-group">
        {{ form.nome_cliente.label }}
        {{ form.nome_cliente(class="form-control") }}
        {{ field_error_messages(form.nome_cliente) }}
      </div>
      <div class="form-group">
        {{ form.endereco.label }}
        {{ form.endereco(class="form-control") }}
        {{ field_error_messages(form.endereco) }}
      </div>
      <div class="form-group">
        {{ form.data_entrega.label }}
        {{ form.data_entrega(class="form-control") }}
        {{ field_error_messages(form.data_entrega) }}
      </div>
      <div class="form-group">
        {{ form.forma_pagamento.label }}
        {{ form.forma_pagamento(class="form-control") }}
        {{ field_error_messages(form.forma_pagamento) }}
      </div>
      <div class="form-group">
        {{ form.observacoes.label }}
        {{ form.observacoes(class="form-control") }}
        {{ field_error_messages(form.observacoes) }}
      </div>
      <br>
      {% for produto in produtos %}
          <div class="form-group form-check">
              <input class="form-check-input" type="checkbox" value="{{ produto.id }}" name="produtos[]">
              <label class="form-check-label mr-2">
                  {{ produto.produto }} - R${{ produto.preco_venda }} - {{ produto.descricao }}
              </label>
              <input type="number" name="quantidades[]" value="1" min="1" max="10" class="form-control" style="width: 60px;">
          </div>
      {% endfor %}
    <hr>
    {{ form.submit(class="btn btn-primary form-control") }}
    </form>
  </div>
</div>


{% endblock %}
{% block javascript %}
{% endblock %}

templates/pedido/pedido.html
{% extends 'base.html' %}
{% from "_error_messages.html" import field_error_messages, error_messages %}
{% block title %}Pedido num. { pedido.id }} - {% endblock %}

{% block content %}
<div class="row">
  <div class="col-lg-9">
    <div class="card mt-4">
      <div class="card-body">
        <h3 class="card-title">Pedido num. {{ pedido.id }}</h3>
        <p class="card-text"><b>Cliente: </b>{{ pedido.nome | safe }} </p>
        <p class="card-text"><b>Data Pedido:</b> {{ pedido.data_pedido }}</p>
        <p class="card-text"><b>Data Entrega:</b> {{ pedido.data_entrega }}</p>
        <p class="card-text"><b>Valor Pedido:</b> {{ "$%.2f" | format(pedido.valor) }}</p>
        <p class="card-text"><b>Status Pagamento:</b> {{ pedido.status_pagamento }}</p>
        <p class="card-text"><b>Status Entrega:</b> {{ pedido.status_entrega }}</p>
        <p class="card-text"><b>Observações: </b>{{ pedido.observacoes }}</p><br>
        <form class="delete-form" method="POST" action="{{ url_for('pedido_bp.delete_pedido', id_pedido=pedido.id, id_cliente='None') }}">
          {{ deletePedido.hidden_tag() }}
          {{ deletePedido.submit(class="btn btn-danger", onclick="return confirm('Are you sure you want to delete this item?');") }}
        </form>
      </div>
    </div>

    <div class="card card-outline-secondary my-4">
      <div class="card-header">
        Produtos para este pedido:
      </div>
      <div class="card-body">
        <hr class="form-border">
        {% if pedido_produto %}
          {% for item in pedido_produto %}
            <b>{{ item.produto }}</b> - {{ item.qtd_produto }} unidades
            <form class="delete-form" method="POST" action="{{ url_for('pedido_bp.delete_pedido_produto', id_pedido=pedido.id, id_produto=item.id_produto) }}">
              {{ deletePedidoProduto.hidden_tag() }}
              {{ deletePedidoProduto.submit(class="btn btn-danger", onclick="return confirm('Are you sure you want to delete this item?');") }}
            </form>
            <br>
          {% endfor %}
        {% else %}
          <p class="placeholder-materia_prima">Insira aqui a os produtos deste pedido.</p>
        {% endif %}
        <hr>
        <form class="pedido-produto_form" action="{{ url_for('pedido_bp.new_pedido_produto') }}" method="POST">
          {{ pedidoProdutoForm.hidden_tag() }}
          {{ error_messages(pedidoProdutoForm.errors) }}
          <div class="form-group">
            {{ pedidoProdutoForm.produto.label }}
            {{ pedidoProdutoForm.produto(class="form-control") }}
            {{ field_error_messages(pedidoProdutoForm.produto) }}
          </div>
          <div class="form-group">
            {{ pedidoProdutoForm.qtd_produto.label }}
            {{ pedidoProdutoForm.qtd_produto(class="form-control") }}
          </div>
          <div class="form-group">
            {{ pedidoProdutoForm.observacoes.label }}
            {{ pedidoProdutoForm.observacoes(class="form-control") }}
          </div>
          {{ pedidoProdutoForm.submit(class="btn btn-primary") }}
          <span class="pedidoproduto-error"></span>
        </form>

      </div>
    </div>
  </div>
</div>
{% endblock %}
{% block javascript %}
{% endblock %}

templates/pedido/pedidos.html
{% extends 'base.html' %}

{% block content %}
  <div class="col-lg-20">
      <div class="row my-5 card-wrapper">
        <table border="1">
        {% if pedidos %}
        {% for pedido in pedidos %}
            <tr><td>
              <p class="card-text">
                <a href="{{ url_for('pedido_bp.pedido', id_pedido=pedido.id) }}">
                  <b>Pedido {{ pedido.id }}</b>
                </a>
                <br>
                <b>Cliente:</b> {{ pedido.cliente }} -
                <b>Data pedido:</b> {{ pedido.data_pedido }} -
                <b>Data entrega:</b> {{ pedido.data_entrega }} -
                <b>Valor:</b> R$ {{ pedido.valor }} -
                <b>Pagamento:</b> {{ pedido.status_pagamento }} -
                <b>Entrega:</b> {{ pedido.status_entrega }}
              </p>
            </td></tr>
        {% endfor %}
        {% else %}
        <h1 class="offset-lg-3">No items to show.</h1>
        {% endif %}
        </table>
      </div>
  </div>
{% endblock %}
{% block javascript %}
{% endblock %}