controllers/produto_final_controller.py
from flask import Blueprint
from flask import Flask, jsonify, render_template, request, url_for, flash, redirect
from Semaninha_MVC.controllers import forms
from Semaninha_MVC.models import produto_final_model, preparo_model, materia_prima_model, utils

# create a blueprint for the produto final routes
produto_final_bp = Blueprint('produto_final_bp', __name__)

def atualiza_custo_produto_preparo(id_preparo, conn):
    # Busca os produtos que utilizam o preparo
    produtos_from_db = produto_final_model.busca_produtos_preparo(id_preparo=id_preparo, conn=conn)

    for produto in produtos_from_db:
        id_produto = produto[0]
        qtd_preparo = produto[1]

        custo_preparo = preparo_model.busca_custo_preparo(id_preparo, conn)
        # Recalcula o custo do preparo dentro da ficha do produto
        custo = round((float(custo_preparo[1]) / float(custo_preparo[0])) * float(qtd_preparo), 2)

        # Atualiza o custo do preparo na ficha do produto
        produto_final_model.update_produto_preparo(id_produto, id_preparo, custo, conn)

        # Atualiza o custo total do produto
        atualiza_custo_produto(id_produto, conn)

def atualiza_custo_produto(id_produto, conn):
    custo_preparos = produto_final_model.busca_custo_total_preparos(int(id_produto), conn)[0]
    custo_embalagens = produto_final_model.busca_custo_total_embalagens(int(id_produto), conn)[0]

    if custo_preparos == None:
        custo_preparos = 0

    if custo_embalagens == None:
        custo_embalagens = 0

    custo = custo_preparos + custo_embalagens

    produto_final_model.update_custo_produto(custo, id_produto, conn)

@produto_final_bp.route("/novo_produto", methods=["GET", "POST"])
def novo_produto():
    conn = utils.get_db()
    form = forms.ProdutoFinalForm()

    form.unidade_medida.choices = utils.unidade_medida_choices(conn)
    form.tipo_produto.choices = utils.busca_tipos_produto(conn)

    if form.validate_on_submit():
        # Process the form data
        inserted_id = produto_final_model.insert(form.produto_final.data,
                                                 form.tipo_produto.data,
                                                 form.unidade_medida.data,
                                                 form.qtd_produto.data,
                                                 form.preco_venda.data,
                                                 form.descricao.data,
                                                 conn)

        # Redirect to some page
        flash("Produto {} inserido com sucesso".format(request.form.get("produto_final")), "success")

        return redirect(url_for('produto_final_bp.produto_final', id_produto_final=inserted_id))

    return render_template("produto_final/novo_produto.html", form=form)

@produto_final_bp.route("/produto_final/<int:id_produto_final>")
def produto_final(id_produto_final):
    conn = utils.get_db()
    produto_from_db = produto_final_model.busca_dados_produto(id_produto_final, conn)

    try:
        produto = {
            "id": produto_from_db[0],
            "produto": produto_from_db[1],
            "unidade_medida": produto_from_db[2],
            "qtd_produto": produto_from_db[3],
            "custo_produto": produto_from_db[4],
            "preco_venda": produto_from_db[5],
            "descricao": produto_from_db[6]
        }
    except:
        produto = {}

    if produto:
        # busca os preparos que compôem o produto
        produto_preparo_from_db = produto_final_model.busca_produto_preparo(id_produto_final, conn)
        produto_preparo = []

        for row in produto_preparo_from_db:
            row = {
                "id_preparo": row[0],
                "preparo": row[1],
                "qtd_preparo": row[2],
                "id": row[3],
                "unidade_medida": row[4],
                "medida_caseira": row[5],
                "custo_preparo": row[6]

            }
            produto_preparo.append(row)

        produtoPreparoForm = forms.NewProdutoPreparoForm()
        produtoPreparoForm.id_produto.data = id_produto_final

        preparos = [(str(preparo[0]), preparo[1]) for preparo in preparo_model.busca_todos_preparos(conn)]
        produtoPreparoForm.preparo.choices = preparos

        deleteProdutoFinal = forms.DeleteButton()
        deletePreparo = forms.DeleteButton()

        return render_template("produto_final/produto_final.html",
                               produtoPreparoForm=produtoPreparoForm,
                               produto=produto,
                               produto_preparo=produto_preparo,
                               deleteProdutoFinal=deleteProdutoFinal,
                               deletePreparo=deletePreparo)
    return redirect(url_for("index"))

@produto_final_bp.route("/produtopreparo/new", methods=["POST"])
def new_produto_preparo():
    conn = utils.get_db()
    form = forms.NewProdutoPreparoForm()

    preparos = [(str(preparo[0]), preparo[1]) for preparo in preparo_model.busca_todos_preparos(conn)]
    form.preparo.choices = preparos

    if form.validate_on_submit():
        produto_final_model.insert_produto_preparo(form, conn)

        #chama a função para atualizar o custo do produto de acordo com os preparos informados
        atualiza_custo_produto(form.id_produto.data, conn)

    return redirect(url_for('produto_final_bp.produto_final', id_produto_final=form.id_produto.data))

@produto_final_bp.route("/produto_embalagem/<int:id_produto>/new", methods=["GET", "POST"])
def produto_embalagem(id_produto):
    conn = utils.get_db()
    form = forms.ProdutoEmbalagemForm()

    embalagens = [(str(embalagem[0]), embalagem[1]) for embalagem
                  in materia_prima_model.busca_embalagens(id_produto, conn)]
    form.materia_prima.choices = embalagens

    if form.validate_on_submit():
        produto_final_model.insert_produto_embalagem(id_produto,
                                                     form.materia_prima.data,
                                                     form.qtd_materia_prima.data,
                                                     form.custo_material.data,
                                                     conn)

        #chama a função para atualizar o custo do produto de acordo com as embalagens informadas
        atualiza_custo_produto(id_produto, conn)

    produto_embalagem=[]
    embalagens_from_db = produto_final_model.busca_produto_embalagem(id_produto, conn)

    for row in embalagens_from_db:
        embalagem = {
            "id_produto": id_produto,
            "produto_final": row[0],
            "id_materia_prima": row[1],
            "materia_prima": row[2],
            "qtd_materia_prima": row[3],
            "custo_material": row[4],
        }
        produto_embalagem.append(embalagem)

    deleteProdutoEmbalagem= forms.DeleteButton()
    produto_from_db = produto_final_model.busca_dados_produto(id_produto,conn)
    produto_final = produto_from_db[1]

    return render_template("produto_final/produto_embalagem.html",
                           id_produto=id_produto,
                           produto_final=produto_final,
                           produto_embalagem=produto_embalagem,
                           produtoEmbalagemForm=form,
                           deleteProdutoEmbalagem=deleteProdutoEmbalagem)

@produto_final_bp.route("/produtopreparo/<int:id_produto>/<int:id_preparo>/delete", methods=["POST"])
def delete_produto_preparo(id_produto, id_preparo):
    conn = utils.get_db()
    produto_final_model.delete_produto_preparo(id_produto, id_preparo, conn)

    id_produto_str = str(id_produto)
    atualiza_custo_produto(id_produto_str, conn)

    flash("Preparo deletado com sucesso.")

    return redirect(url_for('produto_final_bp.produto_final', id_produto_final=id_produto))

@produto_final_bp.route("/produtoembalagem/<int:id_produto>/<int:id_materia_prima>/delete", methods=["POST"])
def delete_produto_embalagem(id_produto, id_materia_prima):
    conn = utils.get_db()
    produto_final_model.delete_produto_embalagem(id_produto, id_materia_prima, conn)

    id_produto_str = str(id_produto)
    atualiza_custo_produto(id_produto_str, conn)

    flash("Embalagem deletada com sucesso.")

    return redirect(url_for('produto_final_bp.produto_embalagem', id_produto=id_produto))

@produto_final_bp.route("/produtos")
def produtos():
    conn = utils.get_db()
    produtos_db = produto_final_model.busca_todos_produtos(conn)

    produtos = []

    for produto in produtos_db:
        ficha = produto_final_model.ficha_tecnica_existe(produto[0], conn)

        if ficha:
            tem_ficha = True
        else:
            tem_ficha = False

        produto = {
            "id"          : produto[0],
            "produto"     : produto[1],
            "preco_venda" : produto[2],
            "descricao"   : produto[3],
            "tem_ficha"   : tem_ficha
        }
        produtos.append(produto)

    return render_template("produto_final/produtos.html", produtos=produtos)

@produto_final_bp.route("/deleteprodutofinal/<int:id_produto>/delete", methods=["POST"])
def delete_produto_final(id_produto):
    conn = utils.get_db()
    produto_final_model.delete_produto_final(id_produto, conn)

    flash("Produto deletado com sucesso.")

    return redirect(url_for('produto_final_bp.produtos'))

templates/produto_final/novo_produto.html
{% extends 'base.html' %}
{% set active_page = 'novo_produto' %}
{% from "_error_messages.html" import field_error_messages, error_messages %}
{% block title %}Novo produto - {% endblock %}

{% block content %}
<div class="row">
  <div class="col-lg-7 offset-lg-2 my-5">
    <h1>Novo produto</h1><hr>
    <form method="POST" action="{{ url_for('produto_final_bp.novo_produto') }}" enctype="multipart/form-data">
      {{ form.hidden_tag() }}
      {{ error_messages(form.errors) }}
      <div class="form-group">
        {{ form.produto_final.label }}
        {{ form.produto_final(class="form-control") }}
        {{ field_error_messages(form.produto_final) }}
      </div>
      <div class="form-group">
        {{ form.tipo_produto.label }}
        {{ form.tipo_produto(class="form-control") }}
        {{ field_error_messages(form.tipo_produto) }}
      </div>
       <div class="form-group">
        {{ form.unidade_medida.label }}
        {{ form.unidade_medida(class="form-control") }}
        {{ field_error_messages(form.unidade_medida) }}
      </div>
       <div class="form-group">
        {{ form.qtd_produto.label }}
        {{ form.qtd_produto(class="form-control", type="number") }}
        {{ field_error_messages(form.qtd_produto) }}
      </div>
      <div class="form-group">
        {{ form.preco_venda.label }}
        {{ form.preco_venda(class="form-control", type="number") }}
        {{ field_error_messages(form.preco_venda) }}
      </div>
      <div class="form-group">
        {{ form.descricao.label }}
        {{ form.descricao(class="form-control", rows="3") }}
        {{ field_error_messages(form.descricao) }}
      </div>
      <hr>
      {{ form.submit(class="btn btn-primary form-control") }}
    </form>
  </div>
</div>
{% endblock %}
{% block javascript %}
<!-- <script src="{{ url_for('static', filename='js/subcategory.js') }}"> </script> -->

{% endblock %}

templates/produto_final/produto_embalagem.html
{% extends 'base.html' %}
{% from "_error_messages.html" import field_error_messages, error_messages %}
{% block title %}{{ produto_final }} - {% endblock %}

{% block content %}
<div class="row">
  <div class="col-lg-9">
    <div class="card card-outline-secondary my-4">
      <div class="card-header">
        <b>Embalagens do produto
        <a href="{{ url_for('produto_final_bp.produto_final', id_produto_final=id_produto) }}">
          {{ produto_final }}</b>
        </a>
      </div>
      <div class="card-body">
        <hr class="form-border">
        {% if produto_embalagem %}
          {% for embalagem in produto_embalagem %}
            <b>{{ embalagem.materia_prima }}</b> - {{ embalagem.qtd_materia_prima }} R$ {{embalagem.custo_materia_prima }}
            <form class="delete-form" method="POST" action="{{ url_for('produto_final_bp.delete_produto_embalagem',
                                                                        id_produto=id_produto,
                                                                        id_materia_prima=embalagem.id_materia_prima) }}">
              {{ deleteProdutoEmbalagem.hidden_tag() }}
              {{ deleteProdutoEmbalagem.submit(class="btn btn-danger", onclick="return confirm('Are you sure you want to delete this item?');") }}
            </form>
            <br>
          {% endfor %}
        {% else %}
          <p class="placeholder-materia_prima"><b>Insira aqui as embalagens do produto.</b></p>
        {% endif %}
        <hr>
        <form class="produto_embalagem_form" action="{{ url_for('produto_final_bp.produto_embalagem',
                                                                 id_produto=id_produto) }}" method="POST">
          {{ produtoEmbalagemForm.hidden_tag() }}
          {{ error_messages(produtoEmbalagemForm.errors) }}
          <div class="form-group">
            {{ produtoEmbalagemForm.materia_prima.label }}
            {{ produtoEmbalagemForm.materia_prima(class="form-control") }}
            {{ field_error_messages(produtoEmbalagemForm.materia_prima) }}
          </div>
          <div class="form-group">
            {{ produtoEmbalagemForm.qtd_materia_prima.label }}
            {{ produtoEmbalagemForm.qtd_materia_prima(class="form-control") }}
          </div>
          <div class="form-group">
            {{ produtoEmbalagemForm.custo_material.label }}
            {{ produtoEmbalagemForm.custo_material(class="form-control", type="number") }}
          </div>
          {{ produtoEmbalagemForm.submit(class="btn btn-primary") }}
          <span class="produtoembalagem-error"></span>
        </form>

      </div>
    </div>
  </div>
</div>
{% endblock %}
{% block javascript %}
<script src="{{ url_for("static", filename="js/custo_materia_prima.js") }}"></script>
{% endblock %}

templates/produto_final/produto_final.html
{% extends 'base.html' %}
{% from "_error_messages.html" import field_error_messages, error_messages %}
{% block title %}{{ produto.produto }} - {% endblock %}

{% block content %}
<div class="row">
  <div class="col-lg-9">
    <div class="card mt-4">
      <div class="card-body">
        <h3 class="card-title">{{ produto.produto }}</h3>
        <p class="card-text"><b>Qtd. produto: </b>{{ produto.qtd_produto | safe }} {{ produto.unidade_medida | safe }}</p>
        <p class="card-text"><b>Custo:</b> {{ "$%.2f" | format(produto.custo_produto) }}</p>
        <p class="card-text"><b>Preço de venda:</b> {{ "$%.2f" | format(produto.preco_venda) }}</p>
        <p class="card-text"><b>Descrição: </b>{{ produto.descricao }}</p><br>
        <a href="{{ url_for('produto_final_bp.produto_embalagem', id_produto=produto.id) }}">
          <p class="card-text"><b>Insira aqui as embalagens do produto</b></p><br><br>
        </a>
        <form class="delete-form" method="POST" action="{{ url_for('produto_final_bp.delete_produto_final', id_produto=produto.id) }}">
          {{ deleteProdutoFinal.hidden_tag() }}
          {{ deleteProdutoFinal.submit(class="btn btn-danger", onclick="return confirm('Are you sure you want to delete this item?');") }}
        </form>
      </div>
    </div>

    <div class="card card-outline-secondary my-4">
      <div class="card-header">
        Composição do produto
      </div>
      <div class="card-body">
        <hr class="form-border">
        {% if produto_preparo %}
          {% for item in produto_preparo %}
            <b>{{ item.preparo }}</b> - {{ item.qtd_preparo }} {{ item.unidade_medida }} R$ {{item.custo_preparo }}
            <form class="delete-form" method="POST" action="{{ url_for('produto_final_bp.delete_produto_preparo', id_produto=produto.id, id_preparo=item.id_preparo) }}">
              {{ deletePreparo.hidden_tag() }}
              {{ deletePreparo.submit(class="btn btn-danger", onclick="return confirm('Are you sure you want to delete this item?');") }}
            </form>
            <br>
          {% endfor %}
        {% else %}
          <p class="placeholder-materia_prima"><b>Insira aqui a os preparos que compõem o produto.</b></p>
        {% endif %}
        <hr>
        <form class="produto_form" action="{{ url_for('produto_final_bp.new_produto_preparo') }}" method="POST">
          {{ produtoPreparoForm.hidden_tag() }}
          {{ error_messages(produtoPreparoForm.errors) }}
          <div class="form-group">
            {{ produtoPreparoForm.preparo.label }}
            {{ produtoPreparoForm.preparo(class="form-control") }}
            {{ field_error_messages(produtoPreparoForm.preparo) }}
          </div>
          <div class="form-group">
            {{ produtoPreparoForm.unidade_medida.label }}
            {{ produtoPreparoForm.unidade_medida(class="form-control") }}
          </div>
          <div class="form-group">
            {{ produtoPreparoForm.qtd_preparo.label }}
            {{ produtoPreparoForm.qtd_preparo(class="form-control") }}
          </div>
          <div class="form-group">
            {{ produtoPreparoForm.medida_caseira.label }}
            {{ produtoPreparoForm.medida_caseira(class="form-control") }}
          </div>
          <div class="form-group">
            {{ produtoPreparoForm.custo_preparo.label }}
            {{ produtoPreparoForm.custo_preparo(class="form-control", type="number") }}
          </div>
          {{ produtoPreparoForm.submit(class="btn btn-primary") }}
          <span class="produtopreparo-error"></span>
        </form>

      </div>
    </div>
  </div>
</div>
{% endblock %}
{% block javascript %}
<script src="{{ url_for("static", filename="js/unid_med_prod.js") }}"></script>
<script src="{{ url_for("static", filename="js/custo_preparo.js") }}"></script>
{% endblock %}

templates/produto_final/produtos.html
{% extends 'base.html' %}

{% block content %}
  <div class="col-lg-9">
      <div class="row my-5 card-wrapper">
        <table border="1">
        {% if produtos %}
        {% for produto in produtos %}
            <tr><td>
              <p class="card-text">
                <a href="{{ url_for('produto_final_bp.produto_final', id_produto_final=produto.id) }}">
                    {{ produto.id }} - {{ produto.produto }}
                    {% if produto.tem_ficha %}
                        - <span class="text-danger"><b>Ficha técnica ok </b></span>
                    {% endif %}
                </a><br>
                Preço: {{ produto.preco_venda }}
              </p>
            </td></tr>
        {% endfor %}
        {% else %}
        <h1 class="offset-lg-3">No items to show.</h1>
        {% endif %}
        </table>
      </div>
  </div>
{% endblock %}
{% block javascript %}
{% endblock %}